version: '2.2'

services:
  shopify:
    image: hieuhidro/shopify:cli-2.33
    volumes:
      - ./theme-custom-dawn:/shopify
      - ./config:/root/.config/shopify/config
      - ./.cache:/root/.cache
    environment: 
# For shopify v3 only
      - SHOPIFY_CLI_NO_ANALYTICS=0
      - SHOPIFY_CLI_THEME_TOKEN=shptka_bd1f24254733aefcccdb96f3b1030ab0
      - SHOPIFY_CLI_TTY=0
      - SHOPIFY_CLI_DEVICE_AUTH=1
      - SHOPIFY_FLAG_STORE=dsbd.test.myshopify.com
# For nginx-proxy 
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
      - SERVER_HOST_IP=127.0.0.1
      - CERT_NAME=default
      - HTTPS_METHOD=redirect
# For nginx-proxy 
    ports:
      - '3456:3456'
      - '9292:9292'
      - '8081:8081'
      - '80:80'
  theme:
    image: hieuhidro/shopify:themekit-1.3.1
    volumes:
      - ./theme-custom-dawn:/shopify
      - ./config:/root/.config/shopify/config
      - ./.cache:/root/.cache
    environment:
      - THEMEKIT_PASSWORD=shptka_bd1f24254733aefcccdb96f3b1030ab0
      - THEMEKIT_THEME_ID=164135534873
      - THEMEKIT_STORE=dsbd.test.myshopify.com
      - SHOPIFY_CLI_DEVICE_AUTH=1
      - 'THEMEKIT_IGNORE_FILES=*.gif:*.jpg:config/settings_data.json'
    ports:
      - '3456:3456'
      - '9292:9292'
      - '8081:8081'
# For nginx-proxy 
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
# For nginx-proxy 
